theme: jekyll-theme-tactile
title: SpaceNet on AWS
description: Spacenet on AWS Dataset Description and download instructions
baseurl: ""
url: "http://spacenetchallenge.github.io"
github_username: dlindenbaum

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

---
title: The SpaceNet Challenge hosted on AWS
description: Accelerating research and innovation in the developement of machine learning algorithms from remote sensing data including satellite imagery
SpaceNet is a partnership between CosmiQ Works, Radiant Solutions, NVIDIA hosted on AWS
url: https://spacenetchallenge.github.io/
logo: /assets/images/SpaceNet-320x320-300x300.png
---

analytics:
  		provider: "google-universal"
  	google:
 	tracking_id: "UA-112217349-1"

