theme: jekyll-theme-tactile
title: SpaceNet on AWS
description: "SpaceNet: Accelerating geospatial machine learning"
baseurl: ""
url: "http://spacenetchallenge.github.io"
github_username: dlindenbaum

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

---
title: SpaceNet: Accelerating geospatial machine learning
description: Accelerating research and innovation in the developement of machine learning algorithms from remote sensing data including satellite imagery
SpaceNet is a partnership between CosmiQ Works, Digital Globe and Radiant Solutions hosted on AWS
url: https://spacenetchallenge.github.io/
logo: /assets/images/SpaceNet-Logo_full-color.png
---

analytics:
  		provider: "google-universal"
  	google:
 	tracking_id: "UA-112217349-1"

